### ISSUE TITLE
onClick event

### ISSUE THREAD

**Issue by peterpuzos** [bgrsquared/d3-react-squared#1]
It would be nice to have an onClick event handler in the example code.  New to D3, so it's a bit tricky to figure out myself.  Or some more in depth documentation on the process of doing it?

**Comment by chroth7** [comment]
You can find two very basic charts in the repo to give examples of the code in d3, a line and a bar charts, see e.g. here: [bar chart](https://github.com/bgrsquared/d3-react-squared/blob/master/apps/charts/barChart.js). In this examples, you have a basic `onEvent` function, [here](https://github.com/bgrsquared/d3-react-squared/blob/master/apps/charts/barChart.js#L226). I hope this gives a good idea on what's going on.

Please have a look and let me know if you need more information!

**Comment by chroth7** [comment]
@peterpuzos you found the code? Please let me know 
(will close this issue soon, otherwise)

thanks
