### ISSUE TITLE
React Version 15.x

### ISSUE THREAD

**Issue by bendiy** [bgrsquared/d3-react-squared#4]
Any plans to support React 15.x?

It might just work out of the box, I haven't tried it yet, but you do set:

```
  "peerDependencies": {
    "react": "^0.14.0"
  }
```

**Comment by chroth7** [comment]
Good point, will look into it asap... been very busy recently, sorry

**Comment by chroth7** [comment]
Thanks for PR - merged it (and updated some more dependencies). Only thing left: update to d3 version 4 (https://github.com/bgrsquared/d3-react-squared/issues/6). 

Also, published to npm, v.0.5.0.
